name: sdk-python

env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync --dev
        working-directory: python/

      # - name: Run tests
      #   run: uv run pytest test/
      #   working-directory: python/
      
      - name: Create .pypirc
        run: |
          echo "[pypi]" > ~/.pypirc
          echo "  username = __token__" >> ~/.pypirc
          echo "  password = $PYPI_TOKEN" >> ~/.pypirc
        shell: bash

      - name: Bump version
        run: |
          uv run bump2version patch
        working-directory: python/

      - name: Publish package to PyPI
        run: |
          make publish
        working-directory: python/